### PR TITLE
Copyediting README.md

### PR DESCRIPTION
**Pull request by KAMiKAZOW**
Only a few trivial changes: Sort distro list in one occurrence alphabetically, use Unicode, add the "--now" parameter where it was missing.

### CODE REVIEW

**Comment by hakavlad** [comment]
`--now` may be not supported in old Systemd versions. You don't need `--now` if you ran `enable` before.

**Comment by KAMiKAZOW** [comment]
The Arch Linux command has --now

**Comment by hakavlad** [comment]
`$ sudo systemctl enable --now nohang` is OK for new systemd versions.

For old versions:

```
$ sudo systemctl enable nohang
$ sudo systemctl start nohang
```

--now may be not supported in old systemd (on CentOS 7).

**Comment by hakavlad** [comment]
Thank you!

**Pull request merged**
